[[levels]]
title = 'clone'
branch = 'main'
solution_checker = 'echo No pushing to master. Read the README file; exit 1'
flags = ['EWU_FLG_IDIDIT']

[[levels]]
title = 'level-1'
branch = 'level-1'
solution_checker = 'hooks/checkers/level-1.sh'
flags = ['EWU_FLG_NOOB']

[[levels]]
title = 'level-2'
branch = 'level-2'
solution_checker = 'hooks/checkers/level-2.sh'
flags = ['EWU_FLG_BETTER']

[[levels]]
title = 'level-3'
branch = 'level-3'
solution_checker = 'hooks/checkers/level-3.sh'
flags = ['EWU_FLG_CRYPTOGENIOUS']

[[levels]]
title = 'level-4'
branch = 'level-4'
solution_checker = 'hooks/checkers/level-4.sh'
flags = ['EWU_FLG_STUDABEST']

[[levels]]
title = 'level-5'
branch = 'level-5'
solution_checker = 'hooks/checkers/level-5.sh'
flags = ['EWU_FLG_AREUSERIOUS']

[[levels]]
title = 'level-6'
branch = 'level-6'
solution_checker = 'hooks/checkers/level-6.sh'
flags = ['EWU_FLG_SPYWARENOMORE']

[[levels]]
title = 'level-7'
branch = 'level-7'
solution_checker = 'hooks/checkers/level-7.sh'
flags = ['EWU_FLG_URINITINGIT']

[[levels]]
title = 'level-8'
branch = 'level-8'
solution_checker = 'hooks/checkers/level-8.sh'
flags = ['EWU_FLG_MERGEKING']

[[levels]]
title = 'level-9'
branch = 'level-9'
solution_checker = 'hooks/checkers/level-9.sh'
flags = ['EWU_FLG_WOWJUSTWOW']

[[levels]]
title = 'level-10'
branch = 'level-10'
solution_checker = 'hooks/checkers/level-10.sh'
flags = ['EWU_FLG_WISHICOULD']

[[levels]]
title = 'level-11'
branch = 'level-11'
solution_checker = 'hooks/checkers/level-11.sh'
flags = ['EWU_FLG_REBASEDIT']
