[[levels]]
title = 'clone'
branch = 'master'
solution_checker = 'echo No pushing to master. Read the README file; exit 1'
flags = ['EWU_FLG_IDIDIT']

[[levels]]
title = 'level-1'
branch = 'main'
solution_checker = 'hooks/checkers/start-here.sh'
flags = ['EWU_FLG_NOOB']

[[levels]]
title = 'level-2'
branch = 'scorpion-treenware-gestatory'
solution_checker = 'hooks/checkers/basic-1.sh'
flags = ['basic-2']

