[[levels]]
title = 'clone'
branch = 'main'
solution_checker = 'echo No pushing to master. Read the README file; exit 1'
flags = ['EWU_FLG_IDIDIT']

[[levels]]
title = 'level-1'
branch = 'level-1'
solution_checker = 'hooks/checkers/level-1.sh'
flags = ['EWU_FLG_NOOB']

[[levels]]
title = 'level-2'
branch = 'level-2'
solution_checker = 'hooks/checkers/level-2.sh'
flags = ['EWU_FLG_BETTER']

[[levels]]
title = 'level-3'
branch = 'level-3'
solution_checker = 'hooks/checkers/level-3.sh'
flags = ['EWU_FLG_CRYPTOGENIOUS']

